name: mean-downstreamer-2
recipe: mean

config:
  build:
    - echo "I am a downstreamer"
  database: mysql

services:
  database:
    type: mean-mysql:8.0

# do not remove this
plugins:
  "@lando/mean": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
